name: test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  hooks_riverpod: ^2.5.1
  hugeicons: ^0.0.7
  latlong2: ^0.9.1
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.5
  shape_of_view_null_safe: ^3.0.0
  flutter_arcore_plugin:
    git:
      url: https://github.com/nabilWafick/flutter_arcore_plugin
      ref: main
  permission_handler: ^11.3.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
